import { Customer } from './customer.model';

export const CUSTOMERS: Customer[] = [
  {
    id: 1,
    firstName: 'James',
    lastName: 'Wilson',
    email: 'jwilson@acmecorp.com',
    phone: '+1-555-0101',
    company: 'Acme Corp',
    position: 'CEO',
    avatar: 'https://i.pravatar.cc/150?u=jameswilson',
    status: 'active',
    source: 'referral',
    tags: ['vip', 'enterprise'],
    notes: 'Key decision maker. Prefers email communication.',
    assignedTo: 1,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-15')
  },
  {
    id: 2,
    firstName: 'Linda',
    lastName: 'Martinez',
    email: 'linda.m@globex.io',
    phone: '+1-555-0102',
    company: 'Globex Industries',
    position: 'VP Sales',
    avatar: 'https://i.pravatar.cc/150?u=lindamartinez',
    status: 'active',
    source: 'website',
    tags: ['tech', 'high-value'],
    notes: 'Interested in enterprise plan.',
    assignedTo: 2,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-06-10')
  },
  {
    id: 3,
    firstName: 'Robert',
    lastName: 'Kim',
    email: 'rkim@initech.com',
    phone: '+1-555-0103',
    company: 'Initech',
    position: 'CTO',
    avatar: 'https://i.pravatar.cc/150?u=robertkim',
    status: 'lead',
    source: 'linkedin',
    tags: ['startup', 'tech'],
    notes: 'Early stage discussions.',
    assignedTo: 3,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-05-20')
  },
  {
    id: 4,
    firstName: 'Patricia',
    lastName: 'Anderson',
    email: 'panderson@umbrellacorp.net',
    phone: '+1-555-0104',
    company: 'Umbrella Corp',
    position: 'Marketing Director',
    avatar: 'https://i.pravatar.cc/150?u=patriciaanderson',
    status: 'active',
    source: 'conference',
    tags: ['enterprise', 'marketing'],
    notes: 'Met at TechSummit 2024.',
    assignedTo: 2,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-12')
  },
  {
    id: 5,
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'mbrown@starkindustries.com',
    phone: '+1-555-0105',
    company: 'Stark Industries',
    position: 'Procurement Manager',
    avatar: 'https://i.pravatar.cc/150?u=michaelbrown',
    status: 'inactive',
    source: 'cold-call',
    tags: ['manufacturing'],
    notes: 'Not interested at this time. Follow up in Q3.',
    assignedTo: 1,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-04-20')
  },
  {
    id: 6,
    firstName: 'Jennifer',
    lastName: 'Lee',
    email: 'jlee@cyberdyne.com',
    phone: '+1-555-0106',
    company: 'Cyberdyne Systems',
    position: 'Engineering Lead',
    avatar: 'https://i.pravatar.cc/150?u=jenniferlee',
    status: 'active',
    source: 'referral',
    tags: ['tech', 'ai', 'vip'],
    notes: 'Very technical. Needs detailed specs.',
    assignedTo: 3,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-06-18')
  },
  {
    id: 7,
    firstName: 'David',
    lastName: 'Taylor',
    email: 'dtaylor@waynecorp.com',
    phone: '+1-555-0107',
    company: 'WayneCorp',
    position: 'Operations Director',
    avatar: 'https://i.pravatar.cc/150?u=davidtaylor',
    status: 'lead',
    source: 'website',
    tags: ['enterprise', 'logistics'],
    notes: 'Requested demo.',
    assignedTo: 2,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-06-01')
  },
  {
    id: 8,
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'mgarcia@lexcorp.com',
    phone: '+1-555-0108',
    company: 'LexCorp',
    position: 'IT Manager',
    avatar: 'https://i.pravatar.cc/150?u=mariagarcia',
    status: 'active',
    source: 'partner',
    tags: ['tech', 'partnership'],
    notes: 'Existing partner. Looking to expand.',
    assignedTo: 1,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-14')
  },
  {
    id: 9,
    firstName: 'Daniel',
    lastName: 'Jackson',
    email: 'djackson@hooli.com',
    phone: '+1-555-0109',
    company: 'Hooli',
    position: 'Product Manager',
    avatar: 'https://i.pravatar.cc/150?u=danieljackson',
    status: 'active',
    source: 'linkedin',
    tags: ['tech', 'startup'],
    notes: 'Evaluating multiple solutions.',
    assignedTo: 3,
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-11')
  },
  {
    id: 10,
    firstName: 'Susan',
    lastName: 'White',
    email: 'swhite@oscorp.com',
    phone: '+1-555-0110',
    company: 'Oscorp Industries',
    position: 'CFO',
    avatar: 'https://i.pravatar.cc/150?u=susanwhite',
    status: 'inactive',
    source: 'conference',
    tags: ['enterprise', 'finance'],
    notes: 'Budget constraints. Revisit next fiscal year.',
    assignedTo: 2,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-05-30')
  },
  {
    id: 11,
    firstName: 'Thomas',
    lastName: 'Harris',
    email: 'tharris@massivedynamic.com',
    phone: '+1-555-0111',
    company: 'Massive Dynamic',
    position: 'Head of Sales',
    avatar: 'https://i.pravatar.cc/150?u=thomasharris',
    status: 'lead',
    source: 'referral',
    tags: ['high-value', 'enterprise'],
    notes: 'Hot lead. Referred by existing customer.',
    assignedTo: 1,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-20')
  },
  {
    id: 12,
    firstName: 'Karen',
    lastName: 'Robinson',
    email: 'krobinson@nimbusdata.com',
    phone: '+1-555-0112',
    company: 'Nimbus Data',
    position: 'Data Architect',
    avatar: 'https://i.pravatar.cc/150?u=karenrobinson',
    status: 'active',
    source: 'website',
    tags: ['tech', 'data'],
    notes: 'Interested in analytics integration.',
    assignedTo: 3,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-06-17')
  },
  {
    id: 13,
    firstName: 'Christopher',
    lastName: 'Moore',
    email: 'cmoore@frobozz.com',
    phone: '+1-555-0113',
    company: 'Frobozz Magic',
    position: 'Owner',
    avatar: 'https://i.pravatar.cc/150?u=christophermoore',
    status: 'active',
    source: 'cold-call',
    tags: ['small-business'],
    notes: 'Small business but growing fast.',
    assignedTo: 2,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-06-16')
  },
  {
    id: 14,
    firstName: 'Amanda',
    lastName: 'Clark',
    email: 'aclark@sprockets.com',
    phone: '+1-555-0114',
    company: 'Sprockets Inc',
    position: 'CEO',
    avatar: 'https://i.pravatar.cc/150?u=amandaclark',
    status: 'lead',
    source: 'partner',
    tags: ['manufacturing', 'partnership'],
    notes: 'Partner referral. Promising opportunity.',
    assignedTo: 1,
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-06-19')
  },
  {
    id: 15,
    firstName: 'Kevin',
    lastName: 'Lewis',
    email: 'klewis@initech.com',
    phone: '+1-555-0115',
    company: 'Initech',
    position: 'Developer',
    avatar: 'https://i.pravatar.cc/150?u=kevinlewis',
    status: 'active',
    source: 'website',
    tags: ['tech', 'developer'],
    notes: 'Technical contact for integration.',
    assignedTo: 3,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-15')
  },
  {
    id: 16,
    firstName: 'Jessica',
    lastName: 'Hall',
    email: 'jhall@vertigo.com',
    phone: '+1-555-0116',
    company: 'Vertigo Corp',
    position: 'VP Engineering',
    avatar: 'https://i.pravatar.cc/150?u=jessicahall',
    status: 'inactive',
    source: 'linkedin',
    tags: ['tech', 'enterprise'],
    notes: 'Went with competitor. Monitor for re-engagement.',
    assignedTo: 2,
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-04-25')
  },
  {
    id: 17,
    firstName: 'Andrew',
    lastName: 'Young',
    email: 'ayoung@megacorp.com',
    phone: '+1-555-0117',
    company: 'MegaCorp',
    position: 'IT Director',
    avatar: 'https://i.pravatar.cc/150?u=andrewwhite',
    status: 'lead',
    source: 'conference',
    tags: ['enterprise', 'vip'],
    notes: 'Met at DevOpsConf. Requested proposal.',
    assignedTo: 1,
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date('2024-06-21')
  },
  {
    id: 18,
    firstName: 'Michelle',
    lastName: 'Wright',
    email: 'mwright@datalake.io',
    phone: '+1-555-0118',
    company: 'DataLake IO',
    position: 'Co-Founder',
    avatar: 'https://i.pravatar.cc/150?u=michellewright',
    status: 'active',
    source: 'referral',
    tags: ['startup', 'tech', 'ai'],
    notes: 'Fast-moving startup. Needs quick implementation.',
    assignedTo: 3,
    createdAt: new Date('2024-06-08'),
    updatedAt: new Date('2024-06-22')
  },
  {
    id: 19,
    firstName: 'William',
    lastName: 'Turner',
    email: 'wturner@bootes.com',
    phone: '+1-555-0119',
    company: 'Bootes Solutions',
    position: 'Sales Director',
    avatar: 'https://i.pravatar.cc/150?u=williamturner',
    status: 'active',
    source: 'website',
    tags: ['tech', 'mid-market'],
    notes: 'Signed up for trial.',
    assignedTo: 2,
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-23')
  },
  {
    id: 20,
    firstName: 'Rachel',
    lastName: 'Adams',
    email: 'radams@phenix.com',
    phone: '+1-555-0120',
    company: 'Phenix Group',
    position: 'Operations Manager',
    avatar: 'https://i.pravatar.cc/150?u=racheladams',
    status: 'lead',
    source: 'partner',
    tags: ['enterprise', 'logistics'],
    notes: 'Partner intro. Follow up with pricing.',
    assignedTo: 1,
    createdAt: new Date('2024-06-12'),
    updatedAt: new Date('2024-06-24')
  }
];
