import { Deal } from './deal.model';

export const DEALS: Deal[] = [
  {
    id: 1,
    title: 'Acme Corp Enterprise Package',
    value: 120000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 80,
    customerId: 1,
    assignedTo: 1,
    expectedCloseDate: new Date('2024-08-15'),
    notes: 'Negotiating custom terms. Very positive.',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-20')
  },
  {
    id: 2,
    title: 'Globex SaaS Subscription',
    value: 45000,
    currency: 'USD',
    stage: 'proposal',
    probability: 60,
    customerId: 2,
    assignedTo: 2,
    expectedCloseDate: new Date('2024-07-30'),
    notes: 'Proposal sent. Awaiting feedback.',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-18')
  },
  {
    id: 3,
    title: 'Initech Startup Plan',
    value: 15000,
    currency: 'USD',
    stage: 'qualification',
    probability: 30,
    customerId: 3,
    assignedTo: 3,
    expectedCloseDate: new Date('2024-09-01'),
    notes: 'Early stage. Need to schedule demo.',
    createdAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-06-01')
  },
  {
    id: 4,
    title: 'Umbrella Corp Marketing Suite',
    value: 78000,
    currency: 'USD',
    stage: 'closed-won',
    probability: 100,
    customerId: 4,
    assignedTo: 2,
    expectedCloseDate: new Date('2024-06-01'),
    notes: 'Deal closed successfully.',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-06-01')
  },
  {
    id: 5,
    title: 'Stark Industries Renewal',
    value: 95000,
    currency: 'USD',
    stage: 'closed-lost',
    probability: 0,
    customerId: 5,
    assignedTo: 1,
    expectedCloseDate: new Date('2024-04-15'),
    notes: 'Lost to competitor. Budget constraints.',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-04-15')
  },
  {
    id: 6,
    title: 'Cyberdyne AI Integration',
    value: 200000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 75,
    customerId: 6,
    assignedTo: 3,
    expectedCloseDate: new Date('2024-08-30'),
    notes: 'Technical evaluation passed. Negotiating pricing.',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-06-22')
  },
  {
    id: 7,
    title: 'WayneCorp Logistics Platform',
    value: 65000,
    currency: 'USD',
    stage: 'proposal',
    probability: 55,
    customerId: 7,
    assignedTo: 2,
    expectedCloseDate: new Date('2024-08-01'),
    notes: 'Proposal under review.',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-15')
  },
  {
    id: 8,
    title: 'LexCorp Infrastructure Upgrade',
    value: 88000,
    currency: 'USD',
    stage: 'closed-won',
    probability: 100,
    customerId: 8,
    assignedTo: 1,
    expectedCloseDate: new Date('2024-05-15'),
    notes: 'Closed. Implementation starting.',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-05-15')
  },
  {
    id: 9,
    title: 'Hooli Analytics Package',
    value: 35000,
    currency: 'USD',
    stage: 'qualification',
    probability: 25,
    customerId: 9,
    assignedTo: 3,
    expectedCloseDate: new Date('2024-09-15'),
    notes: 'Initial meeting scheduled.',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-10')
  },
  {
    id: 10,
    title: 'Massive Dynamic Enterprise Deal',
    value: 150000,
    currency: 'USD',
    stage: 'proposal',
    probability: 65,
    customerId: 11,
    assignedTo: 1,
    expectedCloseDate: new Date('2024-08-20'),
    notes: 'Hot lead. Preparing custom proposal.',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-06-21')
  },
  {
    id: 11,
    title: 'Nimbus Data Storage Solution',
    value: 42000,
    currency: 'USD',
    stage: 'qualification',
    probability: 35,
    customerId: 12,
    assignedTo: 3,
    expectedCloseDate: new Date('2024-10-01'),
    notes: 'Technical discovery call done.',
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date('2024-06-17')
  },
  {
    id: 12,
    title: 'Frobozz Magic POS System',
    value: 12000,
    currency: 'USD',
    stage: 'closed-won',
    probability: 100,
    customerId: 13,
    assignedTo: 2,
    expectedCloseDate: new Date('2024-06-10'),
    notes: 'Small deal but quick close.',
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-06-10')
  },
  {
    id: 13,
    title: 'Sprockets Manufacturing Suite',
    value: 55000,
    currency: 'USD',
    stage: 'qualification',
    probability: 20,
    customerId: 14,
    assignedTo: 1,
    expectedCloseDate: new Date('2024-11-01'),
    notes: 'Initial contact made.',
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-19')
  },
  {
    id: 14,
    title: 'MegaCorp Digital Transformation',
    value: 250000,
    currency: 'USD',
    stage: 'proposal',
    probability: 50,
    customerId: 17,
    assignedTo: 1,
    expectedCloseDate: new Date('2024-09-30'),
    notes: 'Large opportunity. Proposal in progress.',
    createdAt: new Date('2024-06-08'),
    updatedAt: new Date('2024-06-23')
  },
  {
    id: 15,
    title: 'DataLake IO Data Pipeline',
    value: 32000,
    currency: 'USD',
    stage: 'closed-won',
    probability: 100,
    customerId: 18,
    assignedTo: 3,
    expectedCloseDate: new Date('2024-07-01'),
    notes: 'Fast close. Startup needed quick solution.',
    createdAt: new Date('2024-06-12'),
    updatedAt: new Date('2024-06-22')
  }
];
